# Meta programming to allow for seemingly dynamic variable_map mappings

import pdxpy

generate_individual_if_setter = lambda k, n: {k: [{"limit": [f"$index$ = {n}"]}, [
    {"add_to_global_variable_list": {"name": f"variable_map_$name$_index_{n}", "target": "$key$"}},
    {"add_to_global_variable_list": {"name": f"variable_map_$name$_index_{n}", "target": "$value$"}}
    ]
    ]}

generate_individual_if_getter = lambda k, n: {
    k: [
        {"limit": [
            {"is_target_in_global_variable_list": 
                [ {"name": f"variable_map_$name$_index_{n}", "target": "$key$"} ]
            }
        ]},
        {
            "variable_map_get_last_in_list": {
                "name": "$name$",
                "index": n,
                "save_as": "$save_as$"
            }
        }
    ]
}

with open("common/scripted_effects/variable_map_autogenerated.txt", "w") as f: 
    f.write(str(pdxpy.PdxObject(
        {
            "add_to_variable_map_dispatch": [
                generate_individual_if_setter("else_if" if n > 0 else "if", n) for n in range(101)
            ]
        }
    )) + "\n" + str(pdxpy.PdxObject(
        {
            "target_in_map_dispatch": [
                generate_individual_if_getter("else_if" if n > 0 else "if", n) for n in range(101)
            ]
        }
    ))
    )